bar:
  height: 30
  location: top
  background: 00000000
  foreground: 99c8e6ff
  font: "FiraCode Nerd Font:pixelsize=28:weight=medium"
  spacing: 24
  border:
    top-margin: 16
    left-margin: 48
    right-margin: 48

  left:
    - script:
        path: "/home/kd/.config/yambar/scripts/brightnessnow.sh"
        poll-interval: 250
        content:
          - string: {text: "󰃟  {output}"}
    - script:
        path: "/home/kd/.config/yambar/scripts/volnow.sh"
        poll-interval: 250
        content:
          - string: {text: "󱄠 {output}"}
    - script:
        path: "/home/kd/.config/yambar/scripts/network.sh"
        poll-interval: 1000
        content:
          - string: {text: "󰖩  {output}"}
               
  center:
    - script:
        path: /run/current-system/sw/bin/playerctl
        poll-interval: 1000
        args:
           - "--follow"
           - "metadata"
           - "-f"
           - |
             status|string|{{status}}
             artist|string|{{artist}}
             title|string|{{title}}
        content:
          map:
            conditions:
              status == Paused: 
                - string: {text: "󰒮 ", on-click: "playerctl previous"}
                - string: {text: "󰐊 {title}", on-click: "playerctl play-pause"}
                - string: {text: " 󰒭", on-click: "playerctl next"}
              status == Playing:
                - string: {text: "󰒮 ", on-click: "playerctl previous"}
                - string: {text: "󰏤 {title}", on-click: "playerctl play-pause"}  
                - string: {text: " 󰒭", on-click: "playerctl next"}
                
  right:
    - battery:
        name: BAT0
        poll-interval: 1000
        content:
          map:
            default:
              string: {text: "  {capacity}%" }
            conditions:
              state == "charging":
                string: {text: "  {capacity}%"}

    - script:
        path: "/home/kd/.config/yambar/scripts/powernow.sh"
        poll-interval: 1000
        content:
          - string: {text: "  {watts}"}
                                                        
    - clock:
        date-format: "%d %B %Y"
        time-format: "%H%M"
        content:
          - string: {text: "  {date}", right-margin: 12}
          - string: {text: "  {time}"}
